import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const DMSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(DMSans.variable, "font-sans")}>
        <header>
          <div className="flex bg-background-invert text-white items-center gap-2 justify-center py-3">
            <p className="sm:font-bold">Issue with your delivery {">"}</p>
            <a href="/" className={"font-bold text-secondary underline"}>
              Report it here
            </a>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
