// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_collections: dynamic(() => import("./BlogCollections")),
  blog_hero: dynamic(() => import("./BlogHero")),
  call_to_action: dynamic(() => import("./CallToAction")),
  content: dynamic(() => import("./PostContent")),
  featured_blog_posts: dynamic(() => import("./FeaturedBlogPosts")),
  features: dynamic(() => import("./Features")),
  filtered_blog_collections: dynamic(() => import("./FilteredBlogCollections"), { ssr: false }),
  hero: dynamic(() => import("./Hero")),
  //
  contact_form: dynamic(() => import("./ContactForm")),
  map: dynamic(() => import("./Map")),
  //
  partnership_form: dynamic(() => import("./PartnershipForm")),
  report_form: dynamic(() => import("./ReportForm")),
  social_proofs: dynamic(() => import("./Brands")),
  story: dynamic(() => import("./Story")),
  text_with_image: dynamic(() => import("./TextsWithAnimations")),
};
