// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  report_form: dynamic(() => import("./ReportForm")),
  social_proofs: dynamic(() => import("./Brands")),
  story: dynamic(() => import("./Story")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
